name: Publish Release
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup server
      run: touch .env && echo 'DATABASE_URL="postgresql://postgres:notarealpass@localhost:5432/carfinderdb?schema=public"' > .env && yarn install
      working-directory: ./server
    - name: Setup client
      run: yarn install
      working-directory: ./car-app
    - name: Build
      run: yarn build
      working-directory: ./car-app
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: app-master  # default: gh-pages
        publish_dir: ./car-app/build  # default: public
        cname: ceniklas.se/carfinder