name: Publish Release
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      run: yarn install && yarn prisma generate --schema ../prisma/schema.prisma
      working-directory: ./car-app
    - name: Build
      run: yarn build
      working-directory: ./car-app
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: app-master  # default: gh-pages
        publish_dir: ./car-app/build  # default: public
        cname: ceniklas.se/carfinder